source 'https://github.com/CocoaPods/Specs.git'
# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'

target 'XEShopSDKDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for XEShopSDKDemo
    #引入小鹅内嵌课堂SDK
    #pod 'XEShopSDK','2.3.6'
    pod 'XEShopSDK', :path => '../'
    pod 'MBProgressHUD'

end

